### ISSUE TITLE
midi switch settings

### ISSUE THREAD

**Issue by oldmanfury** [AtoVproject/16n-AtoVproject-rework#1]
Can you put some text in the description about how the midi switch is set up?  The original board had K and A written on it for the two swtich positions - Korg and Arturia Beatstep, i.e. MIDI A and MIDI B.  Which position is which?  One of the positions has hash marks under it - is that MIDI A / Korg?

**Comment by ATOVproject** [comment]
Hi,

The positions are described in the user manual.
[https://atovproject.de/manuals/16nrework](https://atovproject.de/manuals/16nrework)

"If the device you want to control follows the type A mini-jack MIDI standard, set the switch to the left. If the device you want to control follows the type B mini-jack MIDI standard, set the switch to the right"

Cheers

**Comment by oldmanfury** [comment]
Wow... can't believe I missed the manual.  Beautifully written BTW.  Sorry about that

**Comment by ATOVproject** [comment]
You didn't miss anything, I just put it online a few days ago!
