### ISSUE TITLE
Update to 1.5?

### ISSUE THREAD

**Issue by MacTuitui** [AtoVproject/16n-AtoVproject-rework#2]
Hi and thanks for the amazing project.

I'm trying to get familiar with the whole process of designing a board, ordering it online (including assembly of smd parts) then finishing the build by manually soldering the bigger parts, looking to replicate this project, and if I ever find a way to improve it (hardware or firmware) I would gladly contribute the changes back.

Very tiny nitpick though is that the kits seem to be at version 1.5 yet the files here still show 1.4. Is there any significant difference between the two? Would you mind if possible publishing the 1.5 version? 

Thanks in advance!

**Comment by ATOVproject** [comment]
The V1.5 is our inhouse production version.

The schematic remains the same. The difference are in package size of some parts and the silkscreen. The 1.4 is more DIY friendly and will therefore remain the version shared on github.

Feel free to produce your own version! Don't forget to share the improvements you made with the same license CC-BY-SA

Cheers
