### ISSUE TITLE
Standoff holes on the pcb do not match the panel files

### ISSUE THREAD

**Issue by rahji** [AtoVproject/16n-AtoVproject-rework#3]
The two standoff holes near the vertical center of the pcb do not match the holes in the panel. Note that the bottom standoff hole is in the right place (as are the holes for the jacks). It's just the two other standoff holes that are misplaced. I found this out after having boards made using the Eagle files in the repo and getting a panel from someone who used the files in the repo. The holes in the panel had to be redrilled to match (since there is a trace too close to the hole in the pcb to widen that hole). The image below overlays the PCB and the front panel BRD files...

![16n_standoff_holes_screenshot](https://user-images.githubusercontent.com/442495/120119542-3f6f0f00-c166-11eb-8f25-69769810d2c7.png)

**Comment by ATOVproject** [comment]
Thanks for raising this up! This is now fixed

**Comment by rahji** [comment]
Do you mean you fixed this for the 1.4 version that's here? (Independent of the 1.5 version that will end up here at some point)

**Comment by ATOVproject** [comment]
I've fixed the file that was already online.
