### ISSUE TITLE
Case holes are in the wrong place

### ISSUE THREAD

**Issue by rahji** [AtoVproject/16n-AtoVproject-rework#4]
The 4 corner holes for the case files are in the wrong place. The image below overlays the pcb, the front panel, and the DXF for the laser cut case. The little grey ticks are the hole positions for the case - you can see how they don't line up with the front panel slots.
![16n_case_holes_screenshot](https://user-images.githubusercontent.com/442495/120119332-2f0a6480-c165-11eb-9a59-db43bceead4c.png).
 I found this after laser cutting using the SVG file. All parts fit together well, but the mounting holes are misplaced. This problem is independent of the material thickness - the problem is that the holes do not line up with the front panel holes (which are based on Eurorack standards).

**Comment by rahji** [comment]
A corrected Adobe Illustrator file...

[16n box 3mm fixed holes AI.zip](https://github.com/AtoVproject/16n-AtoVproject-rework/files/6566877/16n.box.3mm.fixed.holes.AI.zip)

**Comment by ATOVproject** [comment]
Thanks for the sharing the file, it is now shared
